# Database Configuration
database:
  type: "postgresql"  # or "mongodb"
  host: "localhost"
  port: 5432
  name: "econsultation_db"
  username: "admin"
  password: "password"

# Model Configuration
models:
  sentiment:
    name: "ai4bharat/indic-bert"
    cache_dir: "./models/sentiment"
    max_length: 512
    batch_size: 16
    learning_rate: 2e-5
    epochs: 3
    
  summarization:
    extractive:
      method: "textrank"
      top_k: 3
      damping: 0.85
    abstractive:
      name: "t5-small"
      cache_dir: "./models/summarization"
      max_length: 128
      min_length: 30
      beam_size: 4
      
  emotion:
    name: "cardiffnlp/twitter-roberta-base-emotion"
    cache_dir: "./models/emotion"
    labels: ["joy", "anger", "fear", "sadness", "surprise", "neutral"]

# Data Processing Configuration
preprocessing:
  languages: ["hi", "en", "mixed"]
  remove_duplicates: true
  min_length: 10
  max_length: 1000
  clean_html: true
  normalize_text: true
  remove_urls: true
  remove_mentions: true

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  log_level: "info"
  cors_origins: ["*"]
  
# Visualization Configuration
visualization:
  dashboard:
    port: 8501
    theme: "light"
  charts:
    color_palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]
  wordcloud:
    width: 800
    height: 400
    background_color: "white"
    max_words: 100

# Training Configuration
training:
  validation_split: 0.2
  test_split: 0.1
  random_seed: 42
  early_stopping_patience: 3
  save_best_model: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"